name: AI Code Review with xAI

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  review:
    name: Review
    runs-on: ubuntu-latest
    steps:
      - name: Code Review
        uses: tarmojussila/xai-code-review@v0.1.0
        with:
          XAI_API_KEY: ${{xai-92vrbiujPIdzrp15YvGS7DZEYqnbkXrm27cXlXZS6SRBVm1tpgE4JX4cgCG7elK6u8MMEsZknkhjaBjn}}
